name = "tgbot-web-app"
pages_build_output_dir = "./public"
compatibility_date = "2026-08-05"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "tgbot-db"
database_id = "5c734e7c-5ff7-43f2-a0eb-174876adce46"
